# Generated by Django 5.0.1 on 2024-03-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0003_confirmorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmorder',
            name='subtotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmorder',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
