# Generated by Django 5.0.1 on 2024-03-20 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0004_confirmorder_subtotal_confirmorder_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmorder',
            name='product',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='ownerapp.product'),
            preserve_default=False,
        ),
    ]
