# Generated by Django 5.0.1 on 2024-04-02 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0005_confirmorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmorder',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ownerapp.rentals'),
            preserve_default=False,
        ),
    ]
