# Generated by Django 5.0.1 on 2024-04-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0006_confirmorder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmorder',
            name='name',
        ),
    ]
