# Generated by Django 5.0.1 on 2024-05-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0008_finalorder_confirmorder_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='gst',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
