# Generated by Django 4.1.9 on 2026-09-12 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ownerapp', '0009_finalorder_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_rentals', to=settings.AUTH_USER_MODEL),
        ),
    ]
